### ISSUE TITLE
FAQ section in dashboard

### ISSUE THREAD

**Issue by VishnuAmit** [VishnuAmit/LapProFix#12]
# Task Overview
This task focuses on creating a Frequently Asked Questions (FAQ) section for the LapProFix dashboard to provide users with quick answers to common inquiries.

## Your Role
1. Create the FAQ section in the dashboard.
2. Write clear and concise questions and answers.
3. Ensure the FAQ section is visually appealing and easy to navigate.

# Frequently Asked Questions (FAQ)

1. *What services do you offer?*  
   We offer laptop repair, maintenance, and accessories.

2. *How can I track my booking status?*  
   You can track your booking status in the dashboard.

3. *What are your operating hours?*  
   Our operating hours are from 9 AM to 6 PM.

4. *How can I contact support?*  
   You can contact support via email or phone.
   
## Reference

![image](https://github.com/user-attachments/assets/cdf175ba-720b-4074-b8ad-96f420af93b0)

This is sample accordion form. You can use anything you prefer as long as it matches the dashboard  theme and responsive in various screen sizes.

**Comment by Datamaverik** [comment]
Hello @VishnuAmit 
I would love to build the Frequently Asked Questions (FAQ) section for the LapProFix dashboard . I have good experience in front end development on building mobile responsive web apps using React with typescript.

Can you please assign this issue to me under the hacktoberfest label.

**Comment by Datamaverik** [comment]
Hey @VishnuAmit 
I would love to build the  Frequently Asked Questions (FAQ) section for the LapProFix dashboard. I have good experience in front end development, building mobile responsive web apps with React, typescript and Tailwind CSS.

Can you please assign this issue to me under the hacktoberfest label.

**Comment by VishnuAmit** [comment]
hey @Datamaverik . You can start working on it.

**Comment by VishnuAmit** [comment]
Closing this as already this issue has been fixed by @MahendraPachipala .
