### ISSUE TITLE
Sliding testimonials component

### ISSUE THREAD

**Issue by shreyansh1410** [VishnuAmit/LapProFix#23]
![image](https://github.com/user-attachments/assets/1a132477-7ecb-49b4-9187-b662514466bf)

This section will keep on rotating on its own improving the UX of the page.

**Comment by shreyansh1410** [comment]
I can work on it if you assign it to me with the Hacktoberfest tag

**Comment by VishnuAmit** [comment]
@shreyansh1410 Can you please explain what you are trying to do.

**Comment by shreyansh1410** [comment]
It will move like a horizontal slideshow
