### ISSUE TITLE
Fix SignUp/SignIn bugs 

### ISSUE THREAD

**Issue by VishnuAmit** [VishnuAmit/LapProFix#26]
https://drive.google.com/file/d/12MMhHZrPg0wsGen5Dt6EjGamq5cHWI_L/view?usp=sharing

In this video,
- It forces us to sign in/up in order to go to dashboard page. (It's good) ✅
- Normal sign up works and data is getting stored in the database and redirected us to sign in page.✅
- When we sign in with correct credentials or without it, when we click on the sign in button, it goes to 'google sign in page' instead of dashboard. ❌

**Ensure the normal credentials also work fine alongside with the google-auth**

https://drive.google.com/file/d/1PcQC666Y_LnyHwn2nUNa_qiuGOx7IA62/view?usp=sharing

In this video,
- User signs up with google, goes to dashboard directly and data is stored in the DB. ✅ (vishnulakshya - email id)
- When a new user signs in directly, it goes to the dashboard and data is stored (same like sign up) as you can see the whatsappimgs - email id is not present in the database at the time when he is trying to log in. ❌ 

**Change the logic of the *sign in with google* ie when a new user tries to sign in via google, show a warning  'Sign up first'. If its existing user, navigate to the dashboard page**

**Comment by Sakyasekhar** [comment]
I will work on it so you can assign this issue to me

**Comment by VishnuAmit** [comment]
@Sakyasekhar Good work again. I am closing this then.

**Comment by Sakyasekhar** [comment]
> @Sakyasekhar Good work again. I am closing this then.

Thank you!!
