### ISSUE TITLE
 [Refactor]  🔧 Align with Best Practices

### ISSUE THREAD

**Issue by samiurprapon** [VishnuAmit/LapProFix#31]
### Overview 🌟

I’ve come across a few things in the codebase that we can improve for better consistency and collaboration: 

- [x] The `.env` file is not listed in `.gitignore`, which may expose sensitive data. 🔒
- [x] Both `package-lock.json` and `pnpm-lock.yaml` is included, which could cause dependency conflicts. ⚠️ It’s generally best to stick to one package manager. 📦

### 📝 Proposed Changes

- [x] **Add Issue or PR Templates**  
   Implement templates for issues and pull requests to ensure structured development and clearer communication. 🛠️
   
- [x] **Integrate Dependabot**  
   Set up Dependabot to update our dependencies automatically, reducing the risk of security vulnerabilities and compatibility issues. 🔄

- [x] **Dockerize the Application**  
   Create a Docker setup for development purposes, making it easier to run the application consistently across different environments. 🐳

- [x] **Standardize Commit Messages**  
   Establish a proper styling guide for commit messages to enhance clarity and maintainability in our version history. ✏️

### ✅ Benefits

- Enhances collaboration and consistency in our development workflow.
- Helps maintain up-to-date and secure dependencies.
- Simplifies the development environment setup.
- Improves readability and understanding of commit history.

**Comment by VishnuAmit** [comment]
Hey. Thanks for your help. I have merged your recent PR after reviewing it. About issue and pr templates, someone is doing it. Dependabot sounds good. Its good to automatically raise PRs when updates are available.

Shall I close this issue now or do you have anything in your mind?

**Comment by samiurprapon** [comment]
keep this issue open for ongoing communication. It's important to note that we need to migrate to the latest version of Next.js, as the current version (13.x) contains a vulnerability. Additionally, we should create a separate issue for Dockerization.

**Comment by VishnuAmit** [comment]
Yep. Got it.

**Comment by samiurprapon** [comment]
Please check this PR #37 . Add the previous and this PR to this issue.

**Comment by VishnuAmit** [comment]
Sure

**Comment by samiurprapon** [comment]
hey @VishnuAmit please checkout #48
