### ISSUE TITLE
Add "Forgot Password" Page Feature

### ISSUE THREAD

**Issue by MahendraPachipala** [VishnuAmit/LapProFix#33]
Hello,

I noticed that the project is missing a "Forgot Password" functionality. I'd like to contribute by working on this feature. I can implement the following:

A "Forgot Password" page where users can submit their email.
Secure password reset via email.
Please let me know if I can start working on this and submit a PR.

Thanks!

**Comment by VishnuAmit** [comment]
Hey..sure. you can add a small text in the sign up that says forgot password ? And implement the feature.
But note that, We haven't completely integrated mongodb atlas and facing some kind of issues with it about updating the ip address every time when we reopen it. 

So if you are doing this, keep this in mind and try it locally and then with atlas. 
Mention everything in detail while submitting a PR as this issue needs more importance.
