### ISSUE TITLE
[Feature Request] : Update contributors to the README.md

### ISSUE THREAD

**Issue by rajgharat07** [VishnuAmit/LapProFix#46]
### Overview 🌟

I would like to update the profile images of the contributors in the README.md file because I think they appear too small in comparison to the rest of the page and other sections of the README.md.

Please have a look and assign this issue to me under GsSOC'24.
I’ve identified a few improvements that can enhance the consistency and collaboration within our codebase:

- [x] Issue 1: 
- [ ] Issue 2: 

---

### 📝 Proposed Changes

- [x] **Add Contributor Section:**
    - Create a dedicated section in `README.md` to recognize all contributors to the project. 🏅

- [x] **List All Current Contributors:**
     - Add a list or table of contributors with their GitHub profiles or names. This acknowledges their work and provides visibility. 🎖️

- [x] **Include Contributor Images (Optional):**
     - Optionally display GitHub avatars using markdown or a contributors' profile image plugin. 📸

---

### 🎨 Design & Mockup

-

---

### ✅ Benefits

- Improved collaboration and workflow consistency.
- More secure and up-to-date dependencies.
- Streamlined development setup.
- Enhanced version control and history clarity.

---

### 🛠️ Additional Information

- Relevant Links: [Link to documentation, discussions, or issues]
- Related Issues: [Link to any related GitHub issues, if applicable]

**Comment by VishnuAmit** [comment]
Yea @rajgharat07 . You can start doing this.
