### ISSUE TITLE
LapProFix MongoDB Atlas Integration

### ISSUE THREAD

**Issue by VishnuAmit** [VishnuAmit/LapProFix#7]
# *Task Overview*
This task focuses on integrating *MongoDB Atlas* into the *LapProFix* project to replace the current local MongoDB setup. The goal is to ensure seamless data storage and retrieval in a cloud environment.

## *Your Role*
1. *Fork the Repository*  
       Fork the LapProFix repository to your local machine.
   
2. *Install Packages*  
   Navigate to the project directory and install the necessary packages using:
   ```bash
   npm install i

3. *Run the Project*  
   ```bash
   npm run dev

## *What Needs to be Done*

### *Create MongoDB Atlas Account*
Sign up for a MongoDB Atlas account and create a new cluster.  Refer this youtube video: https://www.youtube.com/watch?v=oVHQXwkdS6w (If you don't know to proceed)

### *Configure Database Access*
Set up database access with the appropriate user permissions for your application. (Use the free version)

### *Update Network Access*
Allow connections from your application by configuring the network access settings in MongoDB Atlas.

### *Obtain Connection String*
Get the connection string for your Atlas cluster to connect your application to the database.

### *Run the Project*
Ensure the application is running and can connect to MongoDB Atlas successfully.

## *Output*
- Once the user is signed in, it should get displayed in the atlas database and during sign in, it should cross verify with the database and allow access. ``NOTE: The website is deployed but login and sign up works only in local machine. The changes should be done in order to have login/signup access even when it is deployed.``
- Structure the connection  string in a way, it must be easy to change the connection string just by changing it in` .env `file.

**Comment by Prototype4988** [comment]
Hi @VishnuAmit. Is anyone working on this issue. I would like to work on it if its open

**Comment by VishnuAmit** [comment]
@Prototype4988 . Yea you can start working on it. Use your own connection string from atlas and put it in .env file. Once you done with that, I'll put mine in place of yours and check it if the data is getting stored and retrieved. Good luck !

**Comment by Prototype4988** [comment]
I have done the requested changes. Just a quick question do you get the below error when you try to login with already registered credentials

![image](https://github.com/user-attachments/assets/63988958-aa93-4800-82a2-eafc34188244)

**Comment by VishnuAmit** [comment]
Yep. I get it when I try I open the website and go to sign in first. The error appears. To skip this, you have to go to sign up and create a user and then come to sign in page and login in with any existing users, you will be redirected to dashboard page.

If you have integrated Atlas, Create a PR mentioning everything clearly. Thanks.

**Comment by Prototype4988** [comment]
I have created a PR. you only need to add MONGODB_USERNAME, MONGODB_PASSWORD and MONGODB_CLUSTER in the .env file. mongoDB uri has been dynamically coded in db/config.ts

**Comment by VishnuAmit** [comment]
Yea. Merged it. Thanks.
